### ISSUE TITLE
Preview page throws errors on nuxt generate

### ISSUE THREAD

**Issue by bchiang7** [prismicio-community/nuxt-starter-prismic-blog#1]
Hi there @levimykel, with a fresh clone of this repo I'm getting an error from the preview page when I run `npm run generate`. It seems to be originating from the `api.previewSession` call, which uses the `node-fetch` package. Any ideas how to resolve this?

```
ERROR   /Preview

TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (/Users/brittanychiang/Documents/personal/nuxtjs-blog/node_modules/cross-fetch/node_modules/node-fetch/lib/index.js:1284:9)
    at /Users/brittanychiang/Documents/personal/nuxtjs-blog/node_modules/cross-fetch/node_modules/node-fetch/lib/index.js:1370:19
    at new Promise (<anonymous>)
    at Object.fetch (/Users/brittanychiang/Documents/personal/nuxtjs-blog/node_modules/cross-fetch/node_modules/node-fetch/lib/index.js:1367:9)
    at Object.fetch (/Users/brittanychiang/Documents/personal/nuxtjs-blog/node_modules/cross-fetch/dist/node-ponyfill.js:10:20)
    at /Users/brittanychiang/Documents/personal/nuxtjs-blog/node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:15462
    at u (/Users/brittanychiang/Documents/personal/nuxtjs-blog/node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:15788)
    at t.request (/Users/brittanychiang/Documents/personal/nuxtjs-blog/node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:15965)
    at t.request (/Users/brittanychiang/Documents/personal/nuxtjs-blog/node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:18843)
    at /Users/brittanychiang/Documents/personal/nuxtjs-blog/node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:4349
    at new Promise (<anonymous>)
    at t.previewSession (/Users/brittanychiang/Documents/personal/nuxtjs-blog/node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:4310)
    at asyncData (prismic.config.js:5:0)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by phillysnow** [comment]
Hi @bchiang7 ,

The nuxt plugin does not currently support preview in when generating a static site. For the time being we suggest deploying as a server side rendered app using a service like [Heroku](https://nuxtjs.org/faq/heroku-deployment) .

Thanks,
Phil.

**Comment by bchiang7** [comment]
Gotcha, thanks!

**Comment by TylerOrtiz** [comment]
I realize this is closed and the answer makes sense, but if you wanted to have the `generate` command work with this example you could exclude the Preview route with configuration:

nuxt.config.js:
```
 generate: {
    exclude: [
      /^(?=.*\bPreview\b).*$/
    ]
  }
```

**Comment by phillysnow** [comment]
This sample has now changed, so it works with the generate command. So including the above exclude will break the now break the generate process.

Check out this article for migrating old projects to the new module.
https://prismic.io/docs/vuejs/getting-started/the-new-prismic-nuxt-module
